### ISSUE TITLE
Не поняла к чему этот блок) Удалила, вроде ничего не поменялось)

### ISSUE THREAD

**Issue by igosheva** [SullyWeber/LoftSchool-HTMLCSS-AirPlanet#3]
https://github.com/SullyWeber/LoftSchool-HTMLCSS-AirPlanet/blob/2f073751d7c7cb8e29eaa63553736f7bc3cf39c7/main.html#L76

**Comment by SullyWeber** [comment]
А надо было всего-лишь навести на самолёт :D
